"""
04_speech.py — Sales Speech generated by Dual-Agent
Owner: Engineer 5 (UI)
FIXED: uses modules.ui_theme, not streamlit_app.ui_utils
"""
import time
import streamlit as st
from modules.ui_theme import page_header, badge, no_data_state, get_analysis, page_footer

try:
    from modules.ui_theme import page_header, badge, no_data_state, get_analysis
except ImportError:
    st.error("⚠️ modules/ui_theme.py not found. Verify that you are running from the korhex-ai/ project root.")
    st.stop()

def stream_data(text: str):
    """Generator that emits text chunks with a small delay."""
    if not text:
        return
    for word in text.split(" "):
        if not word:
            continue
        yield word + " "
        time.sleep(0.02)

st.set_page_config(page_title="Sales Speech · KORHEX.AI", page_icon="🎤", layout="wide")

page_header(
    title="🎤 Sales Speech Generator",
    subtitle="Pitch generated by Account Executive Agent and verified by Compliance Auditor — zero hallucinations guaranteed."
)

current = get_analysis()

if not current:
    no_data_state(
        msg="There is no active analysis in this session.",
        hint="← Execute an analysis from the main page first."
    )
    st.stop()

analysis    = current.get("analysis", {})
company     = current.get("company_name", "N/A")
years       = current.get("years_inactive", 0)
speech      = analysis.get("sales_speech") or ""
audit_ok    = analysis.get("audit_passed", False)
audit_notes = analysis.get("audit_notes") or "No audit notes available."
word_count  = analysis.get("word_count", 0) or len(speech.split())
products    = current.get("products", []) or []
ms          = analysis.get("processing_ms", 0)

# ── Audit banner ──────────────────────────────────────────────────────────────
audit_color = "#00FFB2" if audit_ok else "#FF3B5C"
audit_icon  = "✅" if audit_ok else "⚠️"
audit_label = "AUDIT PASSED — Contenido verificado por Compliance Agent" if audit_ok \
              else "AUDIT FLAG — Revisar contenido antes de usar"

st.markdown(f"""
<div style="background:{'#00FFB210' if audit_ok else '#FF3B5C10'};
            border:1px solid {audit_color};border-radius:6px;
            padding:0.8rem 1.2rem;margin-bottom:1rem;
            display:flex;align-items:center;gap:0.8rem;">
    <span style="font-size:1.3rem;">{audit_icon}</span>
    <div>
        <div style="font-weight:700;color:{audit_color};font-size:0.85rem;letter-spacing:0.05em;">{audit_label}</div>
        <div style="color:#C9D1D9;font-size:0.8rem;margin-top:0.2rem;">{audit_notes}</div>
    </div>
</div>
""", unsafe_allow_html=True)

# ── Metrics ───────────────────────────────────────────────────────────────────
st.markdown('<div class="kx-section-title">◈ Pitch Health</div>', unsafe_allow_html=True)
m1, m2, m3, m4 = st.columns(4)
with m1: st.metric("Words", word_count, help="Minimum required: 120")
with m2: st.metric("Referenced products", len(products))
with m3: st.metric("Years inactive", years)
with m4: st.metric("Generation time", f"{ms:,}ms" if ms else "—")

st.markdown("---")

# ── Speech ────────────────────────────────────────────────────────────────────
if not speech:
    no_data_state(
        msg="The sales speech was not generated.",
        hint="Verify that agents.py is running with Ollama active (Terminal 1: ollama serve)."
    )
    st.stop()

def parse_speech_sections(text: str) -> dict:
    sections = {"OPENING": "", "CHALLENGE": "", "SOLUTION": "", "CTA": "", "RAW": ""}
    current_key = "RAW"
    for line in text.split("\n"):
        up = line.upper()
        if "[OPENING"   in up: current_key = "OPENING"
        elif "[CHALLENGE" in up: current_key = "CHALLENGE"
        elif "[SOLUTION"  in up: current_key = "SOLUTION"
        elif "[CTA"       in up: current_key = "CTA"
        else:
            sections[current_key] += line + "\n"
    return sections

parsed       = parse_speech_sections(speech)
has_sections = any(parsed[k].strip() for k in ("OPENING", "CHALLENGE", "SOLUTION", "CTA"))

if has_sections:
    SPEECH_PARTS = [
        ("OPENING",   "🎯 Opening",            "kx-card-accent",
         "A verified insight that captures the buyer’s attention."),
        ("CHALLENGE", "⚡ The Challenge",      "kx-card-red",
         "Specific IT pain points identified in the analysis."),
        ("SOLUTION",  "✅ The Solution",       "kx-card-blue",
         "Two portfolio products with their explicit ROI."),
        ("CTA",       "📅 Call to Action",     "kx-card-yellow",
         "A concrete next step with a target date."),
    ]
    for key, title, card_class, hint in SPEECH_PARTS:
        content = parsed[key].strip()
        if content:
            st.markdown(f"""
            <div class="kx-card {card_class}">
                <div class="kx-section-title">◈ {title}</div>
                <div style="color:#6B7280;font-size:0.73rem;margin-bottom:0.6rem;">{hint}</div>
                <div style="font-size:0.92rem;line-height:1.75;color:#C9D1D9;white-space:pre-wrap;">
            """, unsafe_allow_html=True)
            st.write_stream(stream_data(content))
            st.markdown("""
                </div>
            </div>
            """, unsafe_allow_html=True)

    if parsed["RAW"].strip():
        with st.expander("📄 Full agent transcript"):
            st.markdown('<div class="kx-speech-block">', unsafe_allow_html=True)
            st.write_stream(stream_data(speech))
            st.markdown('</div>', unsafe_allow_html=True)
else:
    st.markdown('<div class="kx-section-title">◈ Full Speech</div>', unsafe_allow_html=True)
    st.markdown('<div class="kx-speech-block">', unsafe_allow_html=True)
    st.write_stream(stream_data(speech))
    st.markdown('</div>', unsafe_allow_html=True)

# ── Copy actions ──────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown('<div class="kx-section-title">◈ Actions</div>', unsafe_allow_html=True)

col_copy, col_info = st.columns([1, 2])
with col_copy:
    if st.button("📋 Copy Speech", use_container_width=True):
        st.code(speech, language=None)
        st.success("✅ Select the text above to copy it.")
with col_info:
    st.markdown("""
    <div style="color:#6B7280;font-size:0.8rem;font-family:'Share Tech Mono',monospace;
                padding:0.6rem;border:1px solid #1E2A35;border-radius:4px;">
        Generated locally with Llama 3 · Verified by Compliance Agent · 0 bytes to the cloud
    </div>
    """, unsafe_allow_html=True)

# ── Referenced products ───────────────────────────────────────────────────────
if products:
    st.markdown("---")
    st.markdown('<div class="kx-section-title">◈ Products Referenced in This Pitch</div>', unsafe_allow_html=True)
    cols = st.columns(min(len(products), 3))
    for i, prod in enumerate(products[:3]):
        with cols[i]:
            st.markdown(f"""
            <div class="kx-card kx-card-accent" style="padding:0.8rem 1rem;">
                <div style="font-weight:700;color:#FFF;font-size:0.9rem;">{prod.get('name','N/A')}</div>
                <div style="color:#6B7280;font-size:0.72rem;font-family:monospace;margin-top:0.2rem;">
                    {prod.get('category','')}
                </div>
            </div>
            """, unsafe_allow_html=True)

page_footer()